- name: install kubernetes cluster
  hosts: all
  become: yes
  become_method: sudo
  become_user: root
  gather_facts: yes
  any_errors_fatal: true

  tasks:
    - include: tasks/tools.yaml
 #     when:
    - include: tasks/conf_machines.yaml
    - include: tasks/conf_containerd.yaml
    - include: tasks/add_kube_key.yaml
    - include: tasks/conf_kubernetes.yaml