- name: Install kubectl 1.28
  hosts: localhost
  gather_facts: false
  any_errors_fatal: true

  tasks:
    - import_tasks: tasks/tools.yaml
    - import_tasks: tasks/add_kube_key.yaml

    - name: Install kubectl 1.28
      become: yes
      apt:
        name: "kubectl={{ version }}"
        state: present