- name: master configuration
  hosts: masters
  become: yes
  become_method: sudo
  become_user: root
  gather_facts: yes
  any_errors_fatal: true

  tasks:
    - import_tasks: tasks/setup_master.yaml