- name: workers configuration
  hosts: workers
  remote_user: ansible
  become: yes
  become_method: sudo
  become_user: root
  gather_facts: yes
  any_errors_fatal: true
  tasks:
    - include: tasks/join_worker-nodes.yaml