- name: Add Google official GPG key
  apt_key:
    url: https://pkgs.k8s.io/core:/stable:/v1.28/deb/Release.key 
    state: present

- name: Add Kubernetes Repository
  apt_repository:
    repo: deb https://pkgs.k8s.io/core:/stable:/v1.28/deb/ 
    state: present
    filename: kubernetes
    mode: 0600

- name: "Update cache & Full system update"
  apt:
    update_cache: true
    upgrade: dist
    cache_valid_time: 3600
    force_apt_get: true
