- name: Remove Docker packages
  apt:
    name: docker-ce docker-ce-cli containerd.io
    state: absent
    purge: yes

- name: Remove Docker directories
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/docker
    - /var/lib/docker
    - /var/run/docker.sock

- name: Remove containerd packages
  apt:
    name: containerd
    state: absent
    purge: yes

- name: Remove containerd directories
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/containerd
    - /var/lib/containerd

- name: "Update cache & Full system update"
  apt:
    update_cache: true
    cache_valid_time: 3600
    force_apt_get: true

