- name: Installing Kubernetes Cluster Packages.
  apt:
    name:
      - "kubeadm={{ version }}"

      - "kubelet={{ version }}"
    state: present
    allow_downgrade: true

- name: Enable service kubelet, and enable persistently
  service:
    name: kubelet
    enabled: yes

- name: load br_netfilter kernel module
  modprobe:
    name: br_netfilter
    state: present

- name: set bridge-nf-call-iptables
  sysctl:
    name: net.bridge.bridge-nf-call-iptables
    value: 1

- name: set ip_forward
  sysctl:
    name: net.ipv4.ip_forward
    value: 1

- name: Reboot all the kubernetes nodes.
  shell: sleep 5 && shutdown -r now "Reboot initiated by Ansible"
  async: 1
  poll: 0
  ignore_errors: true